SELECT "﻿subject_id",
       hadm_id,
       admission_type,
       admission_location,
       discharge_location,
       insurance,
       marital_status,
       race,
       gender,
       anchor_age,
       drug,
       formulary_drug_cd,
       prod_strength,
       dose_val_rx,
       dose_unit_rx,
       form_unit_disp,
       route,
       eventtype,
       careunit,
       order_type,
       order_subtype,
       transaction_type,
       spec_type_desc,
       test_name,
       org_name,
       ab_name,
       comments,
       drg_type,
       description,
       drg_severity,
       drg_mortality
FROM public.patient_records
LIMIT 10000;